### PR TITLE
Snack bar notifications

### LINKED ISSUE #74: Snack Bar Notifications
### User story
As a pet owner, I want to be notified when I am entering a play page without being connected to the car so that I can have a better user experience. 

### Acceptance criteria
- The user is visually snack bar notified when entering a play page without being connected to the car.
- The snack bar notification includes information about how or where the user can connect the car.

### PR DESCRIPTION
**Pull request by InaJ123**
- Added snack bar notifications to play page & race mode. 

Resolves #74

### CODE REVIEW

**Review by olgaratu — APPROVED** [review]
Works fine. Thank you!

**Review by emilieanthony — APPROVED** [review]
Nice work! Just noticed that the new nav bar visually blocks part of the snack bar (it is the same on the auto play page). Can the snack bar be adjusted in some way maybe? I guess that this is a minor UI fix we could look into later if we want to.

**Comment by InaJ123** [comment]
@emilieanthony Yes I agree, I'll try to find a solution for it later!

**Comment by emilieanthony** [comment]
I think the navigation bar is modified in #80 by @olgaratu. I think it looks good, so maybe no need to fix it now @InaJ123?

**Comment by InaJ123** [comment]
Nice! Yes I agree it looks better now @emilieanthony

**Pull request merged**
